### ISSUE TITLE
delay in execute test 

### ISSUE THREAD

**Issue by mostafakh82** [tecnickcom/tcexam#164]
**i have a problem if you could advice me to solve it 
when i run a test from many labs i face delaying in execute test  , it takes more the 15 minutes to start the test 
it depends how many users run the test in the same time or what?
plz if you could help me**

**Comment by peppelinux** [comment]
Hi,

I already seen that problem, in other words it's not a real problem, I think that it's just the question randomization algorithm... I don't know if you need it, I know that putting this patch in the code could speedup the things:

in 

/shared/tce_functions_test.php
at line 1088
put this:

                        $sql = 'SELECT *
			FROM '.K_TABLE_TEST_SUBJSET.'
			WHERE tsubset_test_id='.$test_id.'
                        // peppelinux's patch
			ORDER BY tsubset_test_id ASC';
			//ORDER BY tsubset_type, tsubset_difficulty, tsubset_answers DESC';

try it and tell me if it works as expected. If you want to change its behaviour you just have to customize that sql queries, in this file. Code is well commentend, it should take not so much of your time.

**Comment by mostafakh82** [comment]
dear all

thanx for your replay

i want mention how i grateful using TcExam , wishing to all the best

well about my issue  i must tell you :

- tcexam server  is running under windows 2012 server  with mysql and appache server

- my problem is  ,  sometimes happen when alot of users connect to server   when the try to run exam its take too long time to excute it

sometimes its take more than 30 minutes


well ,  i note that there is Difference in time between clinte  pc  and server time  example :

pc1 start exam at 9:00  am     when i check the resulte for that exam i found the the pc start the exam 2 houre later 7:00 am

is this couse any problem ?

well ,  i used to import users from tsv file   ( is this couse problem )? i mean users details .... or something like this


the code you send to me will work in my case or not ???

please  i need your help  as soon as possible



________________________________

**Comment by nicolaasuni** [comment]
The performance issues are heavily affected by the infrastructure and installation.
First be sure you are using the latest TCExam version.
Then favor a Linux installation over Windows.
Read about MySQL performances.
Eventually you can have multiple TCExam instances running behind a load balancer but the bottleneck is always the database.
If you are starting a test in a classroom, be sure that the users starts in groups instead of all together.
If I remember correctly some people are using TCExam with hundreds of concurrent tests on a single machine installation without experiencing any significant delay.
