### ISSUE TITLE
Execute button not visible in test list.

### ISSUE THREAD

**Issue by A-Gandotra** [tecnickcom/tcexam#180]
I followed the guide to first test but unable to
![capture88](https://user-images.githubusercontent.com/29791157/27723508-cde50b4a-5db0-11e7-85cc-5fb0c080ca7f.PNG)
 see the execute button.

**Comment by salmaabouamod** [comment]
I am facing the same problem, please if you find any solution share it here 
Thanks in advance

**Comment by A-Gandotra** [comment]
Now I am not able to login to the test with the set password now. Any solutions to it ?

**Comment by salmaabouamod** [comment]
I discarded the test with the password and just created a new test without sitting a password in the first place, that's the only way it could work for me 
If you found another solution please let me know 
Good luck

**Comment by A-Gandotra** [comment]
Thanks for your feedback @salmaabouamod  . I tried the same thing and it worked :) Cheers!

**Comment by A-Gandotra** [comment]
Hi @salmaabouamod . Have you been able to find another way to execute the test without changing the date to the previous day?  If yes, can you please share?

Thanks

**Comment by nicolaasuni** [comment]
If a test is expired and it has been already executed, then it can't be modified in order to preserve the test history. A test can eventually modified if all the associated test results are deleted. The pratical way to deal with this scenario is to duplicate the test by changing the name and clicking the "add" button. The new test can then be adjusted accordingly.
