### ISSUE TITLE
Test password not working. Cant execute any test

### ISSUE THREAD

**Issue by maapinho** [tecnickcom/tcexam#181]
Hi,
Today installed TCExam for the first time from a softaculous script. I moved around created module, topics, test, assigned users to groups etc.

When I login as a test taker I see the list of tests, click "execute" and it asks me for the password. I can't get through this screen. No matter what password I put even tried 12345678. I update the test as admin but I always get error "ATTENTION: wrong test password"

I later found this link (https://tcexam.org/docs/first_test/) followed it but noticed it does not have a "password" field in the test configuration

TCExam ver. 14.0.1

**Comment by salmaabouamod** [comment]
I discarded the test with the password and just created a new test without sitting a password in the first place, that's the only way it could work for me
If you found another solution please let me know
Good luck

**Comment by joyful61** [comment]
Hi,
I'm having the same problem. I can't access the test not even with admin privileges, because it requires a specific password.  
In addition, I can't match the test with users though I've selected the students' group. 
I hope to succeed some day. In the meanwhile the only help comes from Indonesian tutorials. I'll keep on watching them.

**Comment by trisnoardi** [comment]
Hi,
in the "shared\code\tce_authorization.php"
I found this code
`if (getPasswordHash($_POST['xtest_password']) == $tph) {....}`
This code is doesn't work, because hash was always changing with this method, so it doesn't can to get true return.

So, i have replaced that with this code:
`if (password_verify($_POST['xtest_password'], $tph)) {...}`

And now, it's works..

*NP, sorry if my english is really bad..

**Comment by nicolaasuni** [comment]
Thanks for reporting this issue, I have fixed  it in TCExam 14.0.2.

**Comment by ethakotasivakumar** [comment]
Hi,
in the "shared\code\tce_authorization.php"
I found the solution change this code
if (getPasswordHash($_POST['xtest_password']) == $tph) {....}


 i have replaced that with this code:
if ((password_verify($_POST['xtest_password'], $tph))==$tph) {...}

And now, it's works perfect
