### ISSUE TITLE
Unknown Error while signing up

### ISSUE THREAD

**Issue by A-Gandotra** [tecnickcom/tcexam#182]
While signing up for a new user, after i fill in all the details and hit the add button, i get the error which says

UNKNOWN ERROR: SMTP CONNECT FAILED

Can anyone help me fix this please?

Thanks

**Comment by nicolaasuni** [comment]
By default  TCExam try to authenticate verify the user email. In order to do so you need to se the SMTP server to be used for sending emails (or disable the user verification - not reccomended).
Check the following configuration files:
* shared/config/tce_user_registration.php
* shared/config/tce_email_config.php
