### ISSUE TITLE
quizz upload

### ISSUE THREAD

**Issue by drNirmaldesai** [tecnickcom/tcexam#242]
How can I import Multiple Choice questions (having pictures) as options? At present, I can import text quiz through TSV file import. It also does not support QTI import.

**Comment by damms005** [comment]
You will notice from that source code that this is not provisioned for at the moment. If you can implement it, you may open a PR

**Comment by drNirmaldesai** [comment]
I am not a technical person and don't know PR is so sorry. But if some can do the import of QTI 1.1 it would be great.

**Comment by damms005** [comment]
I may not have the time to do a [PR](https://en.wikipedia.org/wiki/Distributed_version_control#Pull_requests) for that feature right now. But you can keep an eye on this repo for updates. I do not think the project is so active anymore though, as contributors/authors are not replying to #issues no more. 

Btw, why not use the GUI option, since that already supports pictures (you can run that on a LAN so that more hands can assist in adding the questions). Import already supports Multiple Choice import as TSV. Adding support for pictures in the TSV import is not a trivial task...but not an impossibility though

**Comment by drNirmaldesai** [comment]
Thanks for inputs. Appreciate it.

**Comment by damms005** [comment]
You're welcome. Let me know if you'll need more help

**Comment by nicolaasuni** [comment]
You can achieve similar results by listing the pictures with letters or numbers and provide these as options.
