### ISSUE TITLE
Tcexam test unavailable

### ISSUE THREAD

**Issue by mazydah** [tecnickcom/tcexam#246]
Hello I am having the same issue, the timezone in my server's php.ini file is Africa/Lagos, the server request in shared/config is in UTC

I can view the exams created in d select submenu under the test menu but when I log out and authenticate as a user, it display the no available test
 
Please assist

**Comment by damms005** [comment]
There are more than one factors responsible for tests being displayed for users; which is not restricted to timing/timezone factors alone. So to debug your issue is ambiguous. 
For example, are you sure the right/permission level for taking the concerned test is met by the user account you logged-on with?

**Comment by mazydah** [comment]
well what happened was after completing the tcexam installation and logged in as admin, i was able to create a test which was available. afterwards after logging out as admin. i could no longer login with the admin user credentials i used earlier.

going forward, i checked d db (phpmyadmin) and found the users table with a username as 'anonymous' with an 'encrypted password'. so i tried creating a new user with 'admin' as username with the same privileges i.e. 10. i copied the insert code from install/db-data(#26) and i solved the problem

but afterwards all tests i have created are unavailable to the public. although i can see all tests created on the test selection page.

**Comment by TCexam** [comment]
I had the same problem and with some reverse engineering I found the issue in functions F_isValidIP. It works only for IPv4 and not IPv6

Workaround: Disable in tce_functions_test.php the call to this function line 303-307 (see image) an it works

<img width="507" alt="schermafbeelding 2019-02-21 om 21 47 56" src="https://user-images.githubusercontent.com/47869803/53201297-e7124400-3623-11e9-80b5-5dd94e0619b5.png">

**Comment by damms005** [comment]
Your workaround is strange though because the only function that calls `F_isValidIP` is `F_isValidTestUser` and all IP addresses passed to `F_isValidTestUser` are all converted to IPv6 by the `getNormalizedIP` function in `tce_functions_general.php`.

So if the above is absolutely true and correct in your TCExam installation, `F_isValidIP` should never get an IPv4 address passed to it in the first instance.

It will however be more helpful to this community if you can do some more 'reverse engineering' to know what the issue really is.

**Comment by TCexam** [comment]
Maybe strange, but Quick and Dirty for sure ;-)
In my case disabling call to F_isValidIP solved the issue (no available test). I think it will also help other people with the same issue and therefor I posted this workaround.
I stopt further research because it now works and my first priority is to get better understanding of the functionality and usage of TCexam.
You are right that it will be helpful to this community to know what the issue really is.

**Comment by nicolaasuni** [comment]
Have you tried to set the "authorized IPs" field in Test Managent to "*.*.*.*" ?

**Comment by TCexam** [comment]
Just tried, unfortunately it doesn't work

**Comment by psnayak2007** [comment]
> Your workaround is strange though because the only function that calls `F_isValidIP` is `F_isValidTestUser` and all IP addresses passed to `F_isValidTestUser` are all converted to IPv6 by the `getNormalizedIP` function in `tce_functions_general.php`.
> 
> So if the above is absolutely true and correct in your TCExam installation, `F_isValidIP` should never get an IPv4 address passed to it in the first instance.
> 
> It will however be more helpful to this community if you can do some more 'reverse engineering' to know what the issue really is.

And why don't you come up with a solution by yourself? People are trying rigorously to find a solution in different ways and you keep finding their faults without proper corrections. In this way, your comments are incomplete.

**Comment by damms005** [comment]
@psnayak2007 I do not intend that my comment will go down anyone's throats as a bitter pill. So please don't be bitter about anything. Rather, ask questions to seek clarification.

My comments clearly suggested ideas on how you can better track these issues, since the information provided is not enough to reproduce it, most especially in my [second comment](https://github.com/tecnickcom/tcexam/issues/246#issuecomment-470691298).

Tcexam is such a legacy app built a very long time ago, relatively. I believe if @nicolaasuni is rebuilding this awesome tool today, he would do a lot of things differently, better, and more efficiently. Having said that, you require above beginner-level experience in order to debug some localized problems, more so that if enough information is not provided. I believe it is in the same light that he also suggested not locking user out with the "authorized IPs" options.

So please seek specific clarifications on unclear issues rather than making such unhelpful rants/comments
