### ISSUE TITLE
Please provide a feature to switch editor to HTML WYSIWYG

### ISSUE THREAD

**Issue by andiplusplus** [tecnickcom/tcexam#327]
Hi team, i think the default editor is quite difficult to use. If we use many HTML formatting like bold, italic, underline, etc.
And i think it's an outdated way to edit something to display on web page.
Please provide a way to user to edit the question or answer with HTML WYSIWYG editor. Maybe don't set it to default, but user can switch through config.
Thanks you, regards

**Comment by nicolaasuni** [comment]
The current editor exist on purpose to disallow any dangerous HTML code and provide extra tags for LaTeX, MathML, etc.
The current editor only allow safe formatting tags that can be ported in multiple medium (e.g. print on paper).
It is also compatible with multiple browsers and OSs since 2014!
There are some WYSIWYG BB editors online that I may look into.
