### ISSUE TITLE
Confirm button in test execute page

### ISSUE THREAD

**Issue by teddyvn** [tecnickcom/tcexam#396]
Dear All,
I am confused about the function of confirm button in the test excute page.
I assumed that it is used to marked undoubted answer to return the doubted ones quickly.
However, it doesn't function like this.
Thanks

**Comment by mamans86** [comment]
The function of confirm button as far as i know is to save the answer of the current question number.
You can use the mobile theme of TCExam if you want the functionality like "Unsure" or "doubt" Mark.
But this function only applied on client device only because this function use localStorage to save Unsure answer.

**Comment by mamans86** [comment]
![image](https://user-images.githubusercontent.com/48341998/129531217-45cfb190-cf8d-4964-880f-7d8b0dbc08e5.png)
Picoman theme is available in the default TCEXAM installation, but it is not enabled by default.

**Comment by teddyvn** [comment]
Thanks you for your answer. I also assumed like that but it doesn't function like that in browser version.
I will try Picoman theme as you suggest.
