### ISSUE TITLE
the install.php showing ERROR: create or replace database and get connection........[ERROR: ]

### ISSUE THREAD

**Issue by slim12kg** [tecnickcom/tcexam#95]
when i fill the form for the database settings and click on next. the rest of the config shows ok except for
for this error : create or replace database and get connection........[ERROR: ]

**Comment by infohtreasure** [comment]
‎Check your database username and password Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                                         From: Alofe OluwafemiSent: Monday, January 19, 2015 9:04 AMTo: tecnickcom/tcexamReply To: tecnickcom/tcexamSubject: [tcexam] the install.php showing ERROR: create or replace database and get connection........[ERROR: ] (#95)

—Reply to this email directly or view it on GitHub.

**Comment by slim12kg** [comment]
THIS IS MY DB CONFIG BELOW FROM tce_db_config.php

/**
 * database type (MYSQL, POSTGRESQL, ORACLE)
 */
define ('K_DATABASE_TYPE', 'MYSQL');

/**
 * database Host name (eg: localhost)
 */
define ('K_DATABASE_HOST', 'localhost');

/**
 * database port (eg: 3306, 5432, 1521)
 */
define ('K_DATABASE_PORT', '3306');

/**
 * database name (TCExam)
 */
define ('K_DATABASE_NAME', 'mydatabase');

/**
 * database user name
 */
define ('K_DATABASE_USER_NAME', 'myusername');

/**
 * database user password
 */
define ('K_DATABASE_USER_PASSWORD', 'mypassword');

/**
 * prefix for database tables names
 */
define ('K_TABLE_PREFIX', 'tce_');

i believe the database should be created automatically in my phpmyadmin but since it doesn't. i went ahead to create a database with name tce_ mydatabase. So want could be the problem

**Comment by infohtreasure** [comment]
From your browser (browse to this path and see if you get any error message tce_db_config.php)Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                                         From: Alofe OluwafemiSent: Monday, January 19, 2015 9:32 AMTo: tecnickcom/tcexamReply To: tecnickcom/tcexamCc: infohtreasureSubject: Re: [tcexam] the install.php showing ERROR: create or replace database and get connection........[ERROR: ] (#95)THIS IS MY DB CONFIG BELOW FROM tce_db_config.php

/**


database type (MYSQL, POSTGRESQL, ORACLE)
*/
define ('K_DATABASE_TYPE', 'MYSQL');


/**


database Host name (eg: localhost)
*/
define ('K_DATABASE_HOST', 'localhost');


/**


database port (eg: 3306, 5432, 1521)
*/
define ('K_DATABASE_PORT', '3306');


/**


database name (TCExam)
*/
define ('K_DATABASE_NAME', 'mydatabase');


/**


database user name
*/
define ('K_DATABASE_USER_NAME', 'myusername');


/**


database user password
*/
define ('K_DATABASE_USER_PASSWORD', 'mypassword');


/**


prefix for database tables names
*/
define ('K_TABLE_PREFIX', 'tce_');


i believe the database should be created automatically in my phpmyadmin but since it doesn't. i went ahead to create a database with name tce_ mydatabase. So want could be the problem

—Reply to this email directly or view it on GitHub.

**Comment by nicolaasuni** [comment]
Please be sure that you have created a MySQL user with a password. Users with empty passwords are not supported. Try to log to mysql to see if the user is correctly set:
mysl -uUSER -pPASSWORD
